# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='numOfElements',
            field=models.IntegerField(default=2),
        ),
    ]
