# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170209_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='timetaken',
            field=models.IntegerField(default=0),
        ),
    ]
